/** Type declarations for virtual modules generated by the video vite plugin */

/// <reference types="vite/client" />

declare module 'virtual:egaki-mdx' {
  const mdx: string
  export default mdx
  /** Absolute path of the vite project root, for resolving relative MDX
   *  import sources in <Server> slot rendering (app.tsx). */
  export const projectRoot: string
  /** Absolute path of the MDX entry file. */
  export const entryPath: string
  /** Composition dimensions from frontmatter (default 1920×1080). */
  export const compositionWidth: number
  export const compositionHeight: number
  /** Basename of the project folder, used for the page title. */
  export const folderName: string
}

declare module 'virtual:egaki-modules' {
  export const eagerModules: Record<string, Record<string, any>>
}
